package org.srcgll.lexer;

public enum SymbolCode {
    IF, THEN, ELSE, SKIP, WHILE, PRINT, DO, MULTIPLY, DIVIDE, PLUS, READ,
    MINUS, NOT, AND, OR, LEFT, RIGHT, LEFTCURLY, RIGHTCURLY, LESS, ASSIGN,
    GREAT, LESSOREQ, GREATOREQ, EQ, BOOL, INT, LIT, TEXT, SEMICOLON, EOF
}